server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.27:3306/babytun?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1
  redis:
    host: 192.168.3.27
    port: 6379
    database: 3
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 1000ms

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    #自动的命名驼峰转换
    map-underscore-to-camel-case: true
